# Generated by Django 5.1.4 on 2026-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='rows_suspicious',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='rows_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
