/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006b25',
        'primary-container': '#158635',
        'on-primary': '#ffffff',
        'on-primary-container': '#f7fff2',
        secondary: '#00677c',
        tertiary: '#a23256',
        background: '#f8f9ff',
        'on-background': '#121c2a',
        'on-surface': '#121c2a',
        'on-surface-variant': '#3f4a3d',
        'surface-container': '#e6eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d9e3f6',
        'outline-variant': '#becaba',
        'bg-subtle': '#F9FAFB',
        'scope-1': '#3B82F6',
        'scope-2': '#F97316',
        'scope-3': '#8B5CF6',
        'status-pending': '#6B7280',
        'status-approved': '#10B981',
        'status-flagged': '#F59E0B',
        'status-failed': '#EF4444',
        'surface-tint': '#006e27',
      },
      spacing: {
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        'sidebar-width': '260px',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-lg': ['"DM Sans"', 'sans-serif'],
        'headline-md': ['"DM Sans"', 'sans-serif'],
        'headline-sm': ['"DM Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        xl: '0.75rem',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      width: {
        'sidebar-width': '260px',
      },
    },
  },
  plugins: [],
}
