# Generated by Django 6.0.5 on 2026-05-25 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP (Scope 1)'), ('utility', 'Utility (Scope 2)'), ('travel', 'Travel (Scope 3)')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('factor_kgco2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('source_reference', models.CharField(default='DEFRA 2024', max_length=255)),
            ],
            options={
                'unique_together': {('source_type', 'category', 'subcategory', 'unit', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP (Scope 1)'), ('utility', 'Utility (Scope 2)'), ('travel', 'Travel (Scope 3)')], max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('normalized_quantity_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('emission_kgco2e', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('scope', models.PositiveSmallIntegerField()),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tenants.client')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionfactor')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
